### ISSUE TITLE
Go Concurrency Patterns

### ISSUE THREAD

**Issue by CoinDev** [jcelliott/turnpike#41]
Are there any concurrency patterns or anti patterns that should be known when developing using turnpike?

An informal bench test showed turnpike handling 23k/s local ping requests and I am prepared to go to 4% of that but before I bevel any edges to keep performance throughput going I am curious if there are known patterns to keep requests concurrency and consistency optimal without cutting myself.

Thanks

**Comment by jcelliott** [comment]
> Are there any concurrency patterns or anti patterns that should be known when developing using turnpike?

Nothing specific to turnpike. If you are new to Go in general, I would highly recommend [the concurrency section of "Effective Go"](http://golang.org/doc/effective_go.html#concurrency).

I have been meaning to do some benchmark tests against turnpike, but haven't gotten to that yet. What do you mean by "prepared to go to 4% of that".

Also, are you planning on using WAMP v1 or v2? WAMP v1 has been deprecated, and @beatgammit and I are currently working on the WAMP v2 implementation. You might want to wait until that's done to start using it, because it's a complete rewrite and will probably have completely different performance characteristics.

**Comment by CoinDev** [comment]
> 4% 

I meant that if I was only getting ~900 req/s in a live application with complex components that would be fine.

WAMP v1 is good enough however I am hesitant to add concurrency patterns without clearly understanding the client server session life cycle in the turnpike as tersely mentioned in the other issue I posted.

**Comment by jcelliott** [comment]
I'm not sure I completely understand your concern, but the session life cycle in WAMP is simple. When the client connects, the server assigns a unique session ID that is used until the client disconnects. For WAMP v1 that documentation can be found [here](http://wamp.ws/spec/wamp1/#welcome_message).

If you have more questions feel free to re-open this issue or create a new one.
