### ISSUE TITLE
Calling publish against an autobahn client results in an error

### ISSUE THREAD

**Issue by josephschorr** [jcelliott/turnpike#59]
Calling publish from the Go client:

```
w.client.Publish("myendpoint", values, make(map[string]interface{}))
```

Results in the following error from autobahn:

```
ProtocolError: 'options' in PUBLISH: invalid type <type 'NoneType'>
```

We need to make sure that keys are either not including if `nil`/`None` or that we fill them in with default data (which the spec recommends against doing).

**Comment by jcelliott** [comment]
The 'options' dictionaries are required as far as I can tell (see, for example, [the publish message documentation](https://github.com/tavendo/WAMP/blob/master/spec/basic.md#publish)). Since these are not using any advanced profile features yet, they should be empty. I haven't tested this against autobahn yet, so feel free to re-open if it isn't actually fixed.

**Comment by josephschorr** [comment]
I made a similar change in my client to test it, and it appeared to work, so I suspect this is fine. Will confirm tomorrow.
