### ISSUE TITLE
Embedding sessions into a router

### ISSUE THREAD

**Issue by jzelinskie** [jcelliott/turnpike#64]
If you look at some example Autobahn code or most of the other implementations of WAMP in other languages, they allow you to optionally embed an ApplicationSession directly into a router (i.e. [this autobahn example](https://github.com/tavendo/AutobahnPython/blob/master/examples/asyncio/wamp/beginner/server.py)).What is the best way to reproduce this behavior with the turnpike API?

**Comment by jcelliott** [comment]
Currently the way to do something like that is to use a [`localPeer`](https://github.com/jcelliott/turnpike/blob/v2/session.go#L36). See, for example, how it's used in [router_test.go](https://github.com/jcelliott/turnpike/blob/v2/router_test.go).

It's not very easy to do that right now, so I would love to hear any proposals for a better mechanism. I suppose something like what Autobahn|Python has done could be implemented by embedding a Turnpike-supplied struct into an application-defined one.

**Comment by beatgammit** [comment]
You can now use [Router.GetLocalPeer](https://github.com/jcelliott/turnpike/blob/v2/router.go#L35), but in practice you'd probably get this from [WebsocketServer.GetLocalClient](https://github.com/jcelliott/turnpike/blob/v2/websocket_server.go#L91) (falls back to creating a websocket connection if there's an error making the local client) since the Router isn't exported.

**Comment by jcelliott** [comment]
I think this has been answered well enough. Feel free to open another issue if this isn't sufficient.
